name: ci

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/memorable/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v3
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: './node_modules/.bin/nx test memorable --production'

      - name: Patch version
        run: 'cd ./packages/memorable && npm version patch --git-tag-version=false && cd ../../ && git add . && git commit -am "📦" && npm version patch'

      - name: Push updates
        run: 'git push origin master && git push --tags'

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'memorable.js has been patched 🧠'
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v3
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build memorable
        run: './node_modules/.bin/nx build memorable --production'

      - name: Copy updated package
        run: 'cp -rf ./packages/memorable/package.json ./dist/packages/memorable/package.json'

      - name: Publish memorable package
        run: 'cd ./dist/packages/memorable && npm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ## @todo not working, need to extract version somehow to post on discord. just for fun 😎
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'memorable.js ${{ steps.version.outputs.full }} has been released 🚀'
