name: ci

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/memorable/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        #   fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v3
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: './node_modules/.bin/nx test memorable --production'

      - name: Patch version
        run: 'cd ./packages/memorable && npm version patch'

      - name: Push updates
        run: 'git push origin master && git push --tags'

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'memorable.js has been patched 🧠'
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

       - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/cache@v3
        with:
          path: './node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build memorable
        run: './node_modules/.bin/nx build memorable --production'

      - name: Publish memorable package
        run: 'cd ./dist/packages/memorable && npm publish'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'memorable.js v${{ $MAJOR }}.{{ $MINOR }}.{{ $PATCH }} has been released 🚀'
